/**
 * Renders NOTATION.md into a self-contained HTML page the Worker can serve.
 *
 *   npm run docs
 *
 * The output is committed, and `docs.test.ts` regenerates it in memory and
 * asserts it still matches — so a stale page is a failing test rather than
 * something you find out about in production. `marked` is a devDependency and
 * never reaches the Worker; only the rendered string does.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { marked } from 'marked';

const SOURCE = 'NOTATION.md';
const OUTPUT = 'src/generated/notation.ts';

export function renderPage(markdown: string): string {
  const body = marked.parse(markdown, { async: false, gfm: true });
  return PAGE.replace('{{BODY}}', body);
}

/** Content hash, so a deploy invalidates caches immediately. The page's whole
 *  value is matching the code that answered the roll — serving a stale copy
 *  for an hour would defeat it. */
export function etagFor(html: string): string {
  return `"${createHash('sha256').update(html).digest('hex').slice(0, 16)}"`;
}

/** Styled for both colour schemes, since we cannot know the reader's. */
const PAGE = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Dice notation</title>
<style>
:root { color-scheme: light dark; --fg: #1a1a1a; --bg: #fdfdfc; --muted: #666; --line: #e0e0dc; --code-bg: #f2f2ef; --accent: #7c3aed; }
@media (prefers-color-scheme: dark) {
  :root { --fg: #e8e8e6; --bg: #16161a; --muted: #9a9aa0; --line: #2c2c33; --code-bg: #21212a; --accent: #a78bfa; }
}
* { box-sizing: border-box; }
body { margin: 0 auto; padding: 2.5rem 1.25rem 6rem; max-width: 46rem; background: var(--bg); color: var(--fg);
  font: 16px/1.65 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
h1 { font-size: 2rem; margin: 0 0 1.5rem; letter-spacing: -0.02em; }
h2 { font-size: 1.35rem; margin: 2.75rem 0 0.75rem; padding-top: 1.25rem; border-top: 1px solid var(--line); letter-spacing: -0.01em; }
h3 { font-size: 1.05rem; margin: 1.75rem 0 0.5rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em; }
p, li { overflow-wrap: break-word; }
a { color: var(--accent); }
code { background: var(--code-bg); padding: 0.15em 0.4em; border-radius: 4px; font-size: 0.9em;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
pre { background: var(--code-bg); padding: 1rem 1.15rem; border-radius: 8px; overflow-x: auto; line-height: 1.5; }
pre code { background: none; padding: 0; font-size: 0.875em; }
table { border-collapse: collapse; width: 100%; margin: 1rem 0; display: block; overflow-x: auto; }
th, td { text-align: left; padding: 0.5rem 0.9rem 0.5rem 0; border-bottom: 1px solid var(--line); vertical-align: top; }
th { font-weight: 600; white-space: nowrap; }
del { color: var(--muted); }
blockquote { margin: 1rem 0; padding-left: 1rem; border-left: 3px solid var(--line); color: var(--muted); }
footer { margin-top: 4rem; padding-top: 1.25rem; border-top: 1px solid var(--line); color: var(--muted); font-size: 0.875rem; }
</style>
</head>
<body>
{{BODY}}
<footer>Served by the dice bot itself — this page always matches the deployed version.</footer>
</body>
</html>
`;

// Only write the file when run directly; the test imports renderPage instead.
if (process.argv[1]?.endsWith('build-docs.ts')) {
  const html = renderPage(readFileSync(SOURCE, 'utf8'));
  const module = `// GENERATED by scripts/build-docs.ts from ${SOURCE} — do not edit.
// Run \`npm run docs\` after changing ${SOURCE}; docs.test.ts enforces this.
export const NOTATION_HTML = ${JSON.stringify(html)};
export const NOTATION_ETAG = ${JSON.stringify(etagFor(html))};
`;
  writeFileSync(OUTPUT, module);
  console.log(`Wrote ${OUTPUT} (${html.length} characters of HTML)`);
}
